### ISSUE TITLE
New installation method 

### ISSUE THREAD

**Issue by baboon-king** [zhazhazhu/ni#1]
try fix https://github.com/antfu/ni/issues/181

**Comment by zhazhazhu** [comment]
Please use cargo install npack to install and use

**Comment by baboon-king** [comment]
I am simply a user of "Node.js" and am unfamiliar with what "Cargo" refers to.

**Comment by baboon-king** [comment]
You can provide an install script or install via Homebrew, "Cargo" should not be the only way to install!

**Comment by zhazhazhu** [comment]
We will support Homebrew in the future

**Comment by baboon-king** [comment]
> We will support Homebrew in the future

As of now, it can't be installed via "Homebrew"

**Comment by zhazhazhu** [comment]
You can use curl https://ni.qzzhu.cn/install.sh |Bash, install it. Homebrew currently does not support it, but I still recommend using cargo for installation.

good luck👀
