### ISSUE TITLE
Supported Filtering

### ISSUE THREAD

**Issue by baboon-king** [zhazhazhu/ni#4]
![image](https://github.com/zhazhazhu/ni/assets/63645337/1f3c81d4-cc0e-4479-be17-fc91c7fc2785)
![image](https://github.com/zhazhazhu/ni/assets/63645337/d6e5e8af-1111-47d6-800c-fc81e759d973)

**Comment by zhazhazhu** [comment]
This is a new feature that will be supported in future versions

**Comment by zhazhazhu** [comment]
This feature will be supported in v0.0.11 version. If you need it, please upgrade it
