### ISSUE TITLE
Command not found: npack

### ISSUE THREAD

**Issue by baboon-king** [zhazhazhu/ni#5]
When I create a new terminal I get an error
```shell
/Users/baboon/.zshrc:31: command not found: npack
```

This command comes from the auto-population of ".zshrc" during installation.
```
# npack
export PATH="/Users/baboon/.local/share/.npack:$PATH"
eval "`npack env`"
```
`npack` is an accidental command.

And What is `npack`

![image](https://github.com/zhazhazhu/ni/assets/63645337/7653c903-1183-4903-afc2-8e55291c650f)
![image](https://github.com/zhazhazhu/ni/assets/63645337/d1ae9ad9-e1c2-4ac8-ae1f-aa193a65eb7f)

**Comment by zhazhazhu** [comment]
Fixed installation script, please reinstall
```bash

**Comment by zhazhazhu** [comment]
Fixed installation script, please reinstall
```bash
curl https://ni.qzzhu.cn/install.sh | bash
```

**Comment by baboon-king** [comment]
![image](https://github.com/zhazhazhu/ni/assets/63645337/7653c903-1183-4903-afc2-8e55291c650f)
![image](https://github.com/zhazhazhu/ni/assets/63645337/d1ae9ad9-e1c2-4ac8-ae1f-aa193a65eb7f)
